### ISSUE TITLE
Добавить поля для нагрузочных станций

### ISSUE THREAD

**Issue by andyfollow** [lanitgithub/horizon#42]
В раздел "Home › Хранилище результатов тестов › Нагрузочные станции"
в свойства нагрузочной станции добавить поля
1. Объём памяти Гб
2. Количество ядер штук
3. Объём диска Гб
4. IP (в одну строку)
5. Операционная система (в одну строку)
6. Программное обеспечение (в одну строку)
7. Комментарий (в одну строку)

**Comment by mslacker** [comment]
@andyfollow 
У нас уже есть поле "Описание", его меняем на "Комментарий"? Или ты хочешь два поля "Комментарий" и "Описание"?

**Comment by andyfollow** [comment]
@mslacker я имел ввиду одно поле для комментариев. Можно оставить его как "Описание"
